replicaCount: 1

image:
  repository: ghcr.io/envives/test-api
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  name: test-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-azure
  hosts:
    - host: test-api.dataprovider01.ibtourismdataspace.org
      paths:
        - path: /
          pathType: Prefix

imagePullSecrets:
  - name: ghcr-secret
