replicaCount: 1

image:
  repository: ghcr.io/envives/test-api
  tag: 1.0.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  name: test-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-azure
  hosts:
    - host: test-api.dataprovider01.ibtourismdataspace.org
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: test-api
              port:
                number: 8080
  tls:
    - hosts:
        - test-api.dataprovider01.ibtourismdataspace.org
      secretName: test-api-tls

imagePullSecrets:
  - name: ghcr-secret
