---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-{{ .Values.cluster.namespace }}-svc-account
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app.kubernetes.io/name: openbao-svc-account
    app.kubernetes.io/part-of: openbao
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao-{{ .Values.cluster.namespace }}-role
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app.kubernetes.io/name: openbao-svc-account
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "watch", "list", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao-{{ .Values.cluster.namespace }}-rb
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app.kubernetes.io/name: openbao-svc-account
subjects:
  - kind: ServiceAccount
    name: openbao-{{ .Values.cluster.namespace }}-svc-account
    namespace: {{ .Values.cluster.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openbao-{{ .Values.cluster.namespace }}-role
