apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-api.fullname" . }}
  labels:
    {{- include "test-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "test-api.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
        - name: ghcr-secret